### PR TITLE
Add information about Origin

### PR DESCRIPTION
**Pull request by denispeplin**
I have no idea could be pull request like this accepted, but I've just spend two hours discovering why Corsica doesn't work for given `curl` request and I have something to share.
So I suggest to mention Origin some way in the README.

### CODE REVIEW

**Comment by whatyouhide** [comment]
Hey @denispeplin, thanks for contributing. I am not sure about this because this changes are basically summed up in the very first sentence of the [documentation on hexdocs.pm](https://hexdocs.pm/corsica/Corsica.html):

> Corsica is compliant with the W3C CORS specification. As per this specification, Corsica doesn’t put any CORS response headers in a connection that holds an invalid CORS request.

Maybe we should find a way to make that more prominent (I'm not sure yet) but I am not a fan of the README because the README should only invite users to use Corsica IMO, then if they decide to use it then they should use the documentation as documentation, not the README.

Out of curiosity, you did get logs for Corsica not accepting requests though, right?

**Comment by denispeplin** [comment]
I think that README should contain enough information for basic usage (including some ways to test) and encourage users to explore documentation in case they want that.
Regarding to possibility of accepting the pull request: I'm not sure it is properly formed. It is more an idea than a patch. Of course it's up to owner to make a decision.

**Comment by whatyouhide** [comment]
Hey @denispeplin, I added some more information in the README in https://github.com/whatyouhide/corsica/commit/76f4645ae028533cd7e2d8336e06f405c53f025f. I'm gonna close this as I believe showing a `curl` example is not very beneficial since it's too tied to *how* you used Corsica in your application.

Nevertheless, thanks a lot for contributing! 💟

**Comment by denispeplin** [comment]
Again, I've spent some time searching for the solution. Found in email where this issue was mentioned.
I'm not working with CORS on everyday basis, so this simple info that I have to add `Origin` for CORS to work is hard to find (particularly, in this document: https://www.w3.org/TR/cors/).

The point is not to instruct how to use curl. Point is if you are not using browser to test, nobody will add the `Origin` header for you. This is true for Postman for example.

**Comment by whatyouhide** [comment]
I pushed https://github.com/whatyouhide/corsica/commit/0982f17e86d54faf724c13a40a7ddec5178c34cc. I hope this is enough to show that the `Origin` header is needed. Once again though, the README is just a "tease" of the library and is not supposed to give you enough tools to use it, just enough to get you interested and give you a feel of the library; the documentation should be consulted before writing any line of code that uses Corsica :).

**Comment by denispeplin** [comment]
Looks great, thanks!

**Pull request closed without merging**
